name: Build APK

on:
  push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build the app
        run: ./gradlew assembleDebug assemble
      - name: Upload apk as asset
        uses: actions/upload-artifact@v2
        with:
          name: APKs
          path: ./app/build/outputs/apk/**/*.apk