name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build the app
        run: ./gradlew assemble
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: |
            app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEYSTORE_PW }}
          keyPassword: ${{ secrets.SIGNING_KEY_PW }}
      - name: Upload APK to release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{ steps.sign_app.signedReleaseFile0 }}
            ${{ steps.sign_app.signedReleaseFile1 }}
            ${{ steps.sign_app.signedReleaseFile2 }}